export const videos = [
    { id: 1, url: 'https://www.youtube.com/watch?v=c0hXtJ2vO_k', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 2, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 3, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 4, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 5, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 6, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 7, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 8, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 9, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 10, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 11, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 12, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 13, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 14, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 15, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 16, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 17, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 18, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 19, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 20, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 21, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 22, url: 'https://www.youtube.com/watch?v=XIBdJjahUkM', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
    { id: 23, url: 'https://www.youtube.com/watch?v=avUCPbWppgQ&t=933s', title: 'Como Criar um Chatbot Grátis em Menos de 10 Minutos com a Leadster' , tag: 'Chatbot' },
  ];